"""gae past actual raw

Revision ID: 1740c91fe1f8
Revises: e13794939450
Create Date: 2026-10-04 13:37:56.100272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1740c91fe1f8'
down_revision: Union[str, None] = 'e13794939450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_gae_past_actual_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gl_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sap_gae_past_actual_raw_cost_center'), 'sap_gae_past_actual_raw', ['cost_center'], unique=False)
    op.create_index(op.f('ix_sap_gae_past_actual_raw_fiscal_year'), 'sap_gae_past_actual_raw', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_sap_gae_past_actual_raw_gl_account'), 'sap_gae_past_actual_raw', ['gl_account'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sap_gae_past_actual_raw_gl_account'), table_name='sap_gae_past_actual_raw')
    op.drop_index(op.f('ix_sap_gae_past_actual_raw_fiscal_year'), table_name='sap_gae_past_actual_raw')
    op.drop_index(op.f('ix_sap_gae_past_actual_raw_cost_center'), table_name='sap_gae_past_actual_raw')
    op.drop_table('sap_gae_past_actual_raw')
    # ### end Alembic commands ###
