"""gae cc gl mapping

Revision ID: dee544a23bc8
Revises: 1740c91fe1f8
Create Date: 2026-10-04 13:41:27.062658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dee544a23bc8'
down_revision: Union[str, None] = '1740c91fe1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gae_cc_gl_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_center', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gl_account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manpower', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sub_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gae_cc_gl_mapping_cost_center'), 'gae_cc_gl_mapping', ['cost_center'], unique=False)
    op.create_index(op.f('ix_gae_cc_gl_mapping_gl_account'), 'gae_cc_gl_mapping', ['gl_account'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gae_cc_gl_mapping_gl_account'), table_name='gae_cc_gl_mapping')
    op.drop_index(op.f('ix_gae_cc_gl_mapping_cost_center'), table_name='gae_cc_gl_mapping')
    op.drop_table('gae_cc_gl_mapping')
    # ### end Alembic commands ###
